name: cssResearch
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.7.1
  - asn1crypto=0.24.0
  - astor=0.7.1
  - backcall=0.1.0
  - beautifulsoup4=4.7.1
  - blas=1.0
  - ca-certificates=2019.6.16
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - colorama=0.4.1
  - cryptography=2.7
  - decorator=4.4.0
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - idna=2.8
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - keras-applications=1.0.7
  - keras-preprocessing=1.0.9
  - libmklml=2019.0.3
  - libprotobuf=3.7.1
  - libsodium=1.0.16
  - markdown=3.1
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=2.0.0
  - numpy=1.16.3
  - numpy-base=1.16.3
  - openssl=1.1.1b
  - pandas=0.24.2
  - parso=0.4.0
  - pbr=5.1.3
  - pickleshare=0.7.5
  - pip=19.1.1
  - prompt_toolkit=2.0.9
  - protobuf=3.7.1
  - pycparser=2.19
  - pygments=2.4.0
  - pyopenssl=19.0.0
  - pysocks=1.7.0
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - requests=2.22.0
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - soupsieve=1.8
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tornado=6.0.2
  - traitlets=4.3.2
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - werkzeug=0.15.2
  - wheel=0.33.4
  - wikipedia=1.4.0
  - zeromq=4.3.1
  - zlib=1.2.11
prefix: C:\Users\neiral\Anaconda3\envs\cssResearch
